### PR TITLE
Revert "Support builds on 24.04"

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Reverts tesseract-robotics/colcon-action#11

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason and @marip8 an either of you test this?

**Comment by johnwason** [comment]
No not for this configuration. Not sure if PATH will include the user bin directory by default.

**Comment by johnwason** [comment]
There should be a CI for this repo.

**Comment by Levi-Armstrong** [comment]
@johnwason Do you have a action repo which you setup CI for that I can use as a guide?

**Comment by marip8** [comment]
This doesn't currently work; see [here](https://github.com/ros-industrial/industrial_calibration/actions/runs/9599687817/job/26474065733?pr=197#step:4:1159). I think we need to call `pip` directly with the `--user` flag

**Comment by marip8** [comment]
I still don't think this approach will work for the same reason it didn't work in #11. Here is the output of the failed CI job on 24.04 [here](https://github.com/ros-industrial/industrial_calibration/actions/runs/9599774793/job/26474387989?pr=197).

```
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Error: Process completed with exit code 1.
```

**Comment by Levi-Armstrong** [comment]
Lets then stick with what you have

**Pull request closed without merging**
